### ISSUE TITLE
Change nav-item background color on hover

### ISSUE THREAD

**Issue by BlissMediaSolutions** [htmlstreamofficial/stream-ui-kit#12]
On the website im building, im trying to create the effect that when you hover over a nav-item, the background changes from white to green (in the attached image, i was hovered over "About" when doing the screen capture).
![nav-item hover](https://user-images.githubusercontent.com/10906791/50195283-84d26400-0392-11e9-8868-ef9c8a91ea15.jpg)

Anyway, im trying to make this background color change the full height of the navbar, but i just can't get it to work;
I know the extra padding (top & bottom) which isn't changing color is from the navbar class;
I've been trying css like this, but its not making any difference;
Note: .navbar-custom class just changes the navbar background color to white & adds the border to the bottom.
```
  .navbar .navbar-custom .nav-item:hover .nav-link{
        color: #ffffff;
        background-color: green !important;
    }
```
Any suggestions ?

**Comment by ruslan-garaev** [comment]
Hi,

I've tried this solution:
```
      .navbar-nav .nav-link:hover {
        background-color: green;
        color: #fff;
        transition: background-color .3s ease-in-out, color .1s ease-in-out;
      }
```
It seems it works.

**Comment by BlissMediaSolutions** [comment]
the only difference with that CSS, is that the transition in color is smoother - but it does nothing to make the hover color full height of the navbar.

Here's the HTML of my navbar;
```
<nav class="js-navbar-scroll navbar navbar-expand-lg navbar-light fixed-top navbar-custom">
        <div class="container-fluid">
          <a class="navbar-brand" href="index.html">
            <img src="img/logo-design-new.png" alt="JDC Support" style="width: 40px;">
          </a>

          <button class="navbar-toggler" type="button"
                  data-toggle="collapse"
                  data-target="#navbarTogglerDemo"

                  aria-controls="navbarTogglerDemo"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarTogglerDemo">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0 menu-effects">
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="about">About</a>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="photos">Photos</a>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="pickups">Collections</a>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="careers">Careers</a>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="contact">Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
```

**Comment by ruslan-garaev** [comment]
Yes, you are right – i understood you incorrect.
Try please this code:
```
      .navbar-custom {
        padding-top: 0;
        padding-bottom: 0;
      }
      .navbar-brand {
        padding-top: .8125rem;
        padding-bottom: .8125rem;
      }
      .navbar-nav .nav-link {
        padding-top: 1.1rem;
        padding-bottom: 1.1rem;
        transition: background-color .3s ease-in-out, color .1s ease-in-out;
      }
      .navbar-light .navbar-nav .nav-link:hover {
        background-color: green;
        color: #fff;
      }
```
P.S. May be you should correct values (padding-top, padding-bottom) of the "nav-link" to fill background color to full height.

**Comment by BlissMediaSolutions** [comment]
Thanks heaps!
I ended up changing to this:
```
.navbar-nav .nav-link {
        padding-top: 1.3rem;
        padding-bottom: 1.3rem;
```
and while it isn't completely flush against the top/bottom (as i originally said), i think it looks better with the very thin white space above & below.
![nav-item hover fixed](https://user-images.githubusercontent.com/10906791/50226412-399e6c80-03f7-11e9-9495-2365b59de71d.jpg)
