### ISSUE TITLE
Is FF officially supported?

### ISSUE THREAD

**Issue by skydan** [htmlstreamofficial/stream-ui-kit#4]
Amazing work guys!

I've spotted minor issue with toggles under FF 60.0.2 (64-bit):
<img width="559" alt="image" src="https://user-images.githubusercontent.com/372686/41886708-65c900ac-78b2-11e8-9811-1bc763e07e17.png">

So is FF officially supported or it's Chrome only? Sorry, didn't find browserlist's config in the repo.

**Comment by jahaganiev** [comment]
Duplicated #3 

Hi @skydan, thank you for your message. Yes, we do support FF and this issue is already fixed and will be added in coming update within a few days.
