### ISSUE TITLE
Show website

### ISSUE THREAD

**Issue by fireinrain** [htmlstreamofficial/stream-ui-kit#7]
![215ceeba62b89b91bbde1f848aeed49](https://user-images.githubusercontent.com/14249262/42483504-7aae3090-8420-11e8-83d0-2662711e39a9.png)
 
hey dude,I visit the website that you offered and i find some of the check elements are not in the right
position. The UI seems very nice,but please fix this bug.Thanks.

**Comment by jahaganiev** [comment]
Hey, thank you for reporting it. We're aware of this issue and already has been fixed. We will include this fix in coming update soon. Meanwhile, you may get the fixed CSS file from here on github page.
