### ISSUE TITLE
When use my own logo, nav text will not center

### ISSUE THREAD

**Issue by huangdun** [htmlstreamofficial/stream-ui-kit#8]
When use my own logo, nav text will not center

**Comment by jahaganiev** [comment]
Hi @huangdun, could you please provide us some screenshots of the issue? Thanks!

**Comment by huangdun** [comment]
Sorry, I couldn't replicate it now. I think I was trying to use svg code, the nav text will off center slightly higher than the logo.

**Comment by jahaganiev** [comment]
Please provide us more details about the issue if not we can not help you without information.

**Comment by jahaganiev** [comment]
Closing this question as have not received any details to clearly describe the issue.
